export const teacherNavItems = [
  { href: '/', label: 'Overview', icon: '🏫' },
  { href: '/dashboard', label: 'Dashboard', icon: '📊' },
  { href: '/students', label: 'Students', icon: '👩‍🏫' },
  { href: '/classes', label: 'Classes', icon: '🧒' },
  { href: '/attendance', label: 'Attendance', icon: '✅' },
  { href: '/homework', label: 'Homework', icon: '📝' },
  { href: '/spelling-challenges', label: 'Spelling', icon: '✍️' },
  { href: '/quiz-creator', label: 'Quiz Creator', icon: '🧠' },
  { href: '/lesson-planner', label: 'Lesson Planner', icon: '🗂️' },
  { href: '/worksheet-generator', label: 'Worksheet Generator', icon: '📄' },
  { href: '/exam-paper-generator', label: 'Exam Paper Generator', icon: '🧾' },
  { href: '/marking-assistant', label: 'Marking Assistant', icon: '✅' },
  { href: '/parent-communication-reporting', label: 'Parent Reporting', icon: '👨‍👩‍👧' },
  { href: '/ai-assistant', label: 'AI Assistant', icon: '🤖' },
  { href: '/reports', label: 'Reports', icon: '📈' },
  { href: '/settings', label: 'Settings', icon: '⚙️' },
];
